---
- name: copy ceph admin keyring
  copy:
    src: "{{ fetch_directory }}/{{ fsid }}/etc/ceph/{{ cluster }}.client.admin.keyring"
    dest: "/etc/ceph/"
    owner: "ceph"
    group: "ceph"
    mode: "0600"
  when: cephx
